version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: clinica_postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: clinica_user
      POSTGRES_PASSWORD: clinica_pass
      POSTGRES_DB: clinica_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
